version: "3.9"
services:
  website:
    image: pavankumar6/website:v1.0.5-arm64
    ports:
      - "8080"
    volumes:
      -  ./website.db:/opt/app/website.db
      -  ./static:/opt/app/static
    restart: on-failure
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.100'
          memory: 200M
        reservations:
          cpus: '0.50'
          memory: 100M
  nginx:
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: '0.100'
          memory: 200M
        reservations:
          cpus: '0.50'
          memory: 100M
    depends_on:
      - website
    ports:
      - "80:80"
